CREATE TABLE IF NOT EXISTS `biopool_services` (
  `id` int AUTO_INCREMENT NOT NULL,
  `name` varchar(180) NOT NULL,
  `slug` varchar(180) NOT NULL,
  `description` mediumtext,
  `status` enum('draft','published','hidden','archived') NOT NULL DEFAULT 'draft',
  `capacity` int NOT NULL DEFAULT 40,
  `opening_time` varchar(5) NOT NULL DEFAULT '10:00',
  `water_close_time` varchar(5) NOT NULL DEFAULT '21:30',
  `facility_close_time` varchar(5) NOT NULL DEFAULT '22:00',
  `first_entry_time` varchar(5) NOT NULL DEFAULT '10:00',
  `last_entry_time` varchar(5) NOT NULL DEFAULT '18:00',
  `slot_interval_minutes` int NOT NULL DEFAULT 60,
  `standard_duration_minutes` int NOT NULL DEFAULT 240,
  `final_entry_duration_minutes` int NOT NULL DEFAULT 210,
  `booking_horizon_months` int,
  `customer_can_cancel` int NOT NULL DEFAULT 0,
  `customer_can_reschedule` int NOT NULL DEFAULT 0,
  `max_staff_reschedules` int NOT NULL DEFAULT 2,
  `refund_notice_hours` int NOT NULL DEFAULT 72,
  `reschedule_notice_hours` int NOT NULL DEFAULT 48,
  `refund_fee_percent` decimal(5,2) NOT NULL DEFAULT '0.25',
  `child_min_age` int NOT NULL DEFAULT 5,
  `child_max_age` int NOT NULL DEFAULT 12,
  `child_requires_adult` int NOT NULL DEFAULT 1,
  `reminder_hours_before` int NOT NULL DEFAULT 24,
  `reminder_email_enabled` int NOT NULL DEFAULT 1,
  `reminder_whatsapp_enabled` int NOT NULL DEFAULT 1,
  `notification_email` varchar(320) NOT NULL DEFAULT 'contacto@cancagua.cl',
  `maps_url` text,
  `rules_url` text,
  `confirmation_email_subject` varchar(250),
  `confirmation_email_body` mediumtext,
  `reminder_email_subject` varchar(250),
  `reminder_email_body` mediumtext,
  `reminder_whatsapp_body` mediumtext,
  `created_by_user_id` int,
  `archived_at` timestamp,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_services_id` PRIMARY KEY (`id`),
  CONSTRAINT `biopool_services_slug_unique` UNIQUE (`slug`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `biopool_ticket_types` (
  `id` int AUTO_INCREMENT NOT NULL,
  `service_id` int NOT NULL,
  `code` varchar(40) NOT NULL,
  `name` varchar(120) NOT NULL,
  `price_clp` int NOT NULL,
  `minimum_age` int,
  `maximum_age` int,
  `requires_adult` int NOT NULL DEFAULT 0,
  `display_order` int NOT NULL DEFAULT 0,
  `active` int NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_ticket_types_id` PRIMARY KEY (`id`),
  CONSTRAINT `biopool_ticket_types_service_code_unique` UNIQUE (`service_id`, `code`),
  INDEX `biopool_ticket_types_service_idx` (`service_id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `biopool_schedules` (
  `id` int AUTO_INCREMENT NOT NULL,
  `service_id` int NOT NULL,
  `day_of_week` int NOT NULL,
  `enabled` int NOT NULL DEFAULT 1,
  `opening_time` varchar(5) NOT NULL DEFAULT '10:00',
  `first_entry_time` varchar(5) NOT NULL DEFAULT '10:00',
  `last_entry_time` varchar(5) NOT NULL DEFAULT '18:00',
  `water_close_time` varchar(5) NOT NULL DEFAULT '21:30',
  `facility_close_time` varchar(5) NOT NULL DEFAULT '22:00',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_schedules_id` PRIMARY KEY (`id`),
  CONSTRAINT `biopool_schedules_service_day_unique` UNIQUE (`service_id`, `day_of_week`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `biopool_service_images` (
  `id` int AUTO_INCREMENT NOT NULL,
  `service_id` int NOT NULL,
  `url` text NOT NULL,
  `alt_text` varchar(250),
  `display_order` int NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_service_images_id` PRIMARY KEY (`id`),
  INDEX `biopool_service_images_service_idx` (`service_id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `biopool_blocks` (
  `id` int AUTO_INCREMENT NOT NULL,
  `service_id` int NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `start_time` varchar(5) NOT NULL DEFAULT '10:00',
  `end_time` varchar(5) NOT NULL DEFAULT '22:00',
  `blocked_capacity` int NOT NULL DEFAULT 40,
  `reason` enum('technical','temperature','private_event','maintenance','other') NOT NULL,
  `notes` text,
  `reference_type` varchar(40),
  `reference_id` varchar(80),
  `active` int NOT NULL DEFAULT 1,
  `created_by_user_id` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_blocks_id` PRIMARY KEY (`id`),
  INDEX `biopool_blocks_service_dates_idx` (`service_id`, `start_date`, `end_date`, `active`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `biopool_bookings` (
  `id` int AUTO_INCREMENT NOT NULL,
  `booking_code` varchar(32) NOT NULL,
  `service_id` int NOT NULL,
  `client_id` int,
  `client_name` varchar(200) NOT NULL,
  `client_email` varchar(320) NOT NULL,
  `client_phone` varchar(40) NOT NULL,
  `booking_date` date NOT NULL,
  `start_time` varchar(5) NOT NULL,
  `end_time` varchar(5) NOT NULL,
  `adult_quantity` int NOT NULL DEFAULT 1,
  `child_quantity` int NOT NULL DEFAULT 0,
  `total_guests` int NOT NULL,
  `status` enum('pending','confirmed','completed','cancelled','no_show') NOT NULL DEFAULT 'pending',
  `attendance_confirmation` enum('pending','confirmed','declined') NOT NULL DEFAULT 'pending',
  `attendance_token` varchar(64) NOT NULL,
  `payment_status` enum('pending','paid','partially_refunded','refunded') NOT NULL DEFAULT 'pending',
  `payment_method` varchar(60),
  `payment_reference` varchar(160),
  `original_amount_clp` int NOT NULL,
  `discount_amount_clp` int NOT NULL DEFAULT 0,
  `amount_paid_clp` int NOT NULL DEFAULT 0,
  `refund_amount_clp` int NOT NULL DEFAULT 0,
  `refund_fee_amount_clp` int NOT NULL DEFAULT 0,
  `refund_status` enum('none','pending','processed','rejected') NOT NULL DEFAULT 'none',
  `refund_fee_percent` decimal(5,2) NOT NULL DEFAULT '0.25',
  `source` enum('cms','web','skedu_import','b2b') NOT NULL DEFAULT 'cms',
  `reschedule_count` int NOT NULL DEFAULT 0,
  `notes` text,
  `cancellation_reason` text,
  `cancelled_at` timestamp,
  `cancelled_by_user_id` int,
  `created_by_user_id` int,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_bookings_id` PRIMARY KEY (`id`),
  CONSTRAINT `biopool_bookings_code_unique` UNIQUE (`booking_code`),
  CONSTRAINT `biopool_bookings_attendance_token_unique` UNIQUE (`attendance_token`),
  INDEX `biopool_bookings_service_date_idx` (`service_id`, `booking_date`, `status`),
  INDEX `biopool_bookings_client_idx` (`client_id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `biopool_booking_activity` (
  `id` int AUTO_INCREMENT NOT NULL,
  `booking_id` int NOT NULL,
  `action` varchar(80) NOT NULL,
  `detail` text,
  `user_id` int,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_booking_activity_id` PRIMARY KEY (`id`),
  INDEX `biopool_booking_activity_booking_idx` (`booking_id`, `created_at`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `biopool_notifications` (
  `id` int AUTO_INCREMENT NOT NULL,
  `booking_id` int NOT NULL,
  `type` enum('confirmation','reminder') NOT NULL,
  `channel` enum('email','whatsapp') NOT NULL,
  `status` enum('pending','sending','sent','failed','skipped') NOT NULL DEFAULT 'pending',
  `scheduled_at` timestamp,
  `sent_at` timestamp,
  `provider_id` varchar(180),
  `error` text,
  `attempt_count` int NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `biopool_notifications_id` PRIMARY KEY (`id`),
  INDEX `biopool_notifications_queue_idx` (`status`, `scheduled_at`),
  INDEX `biopool_notifications_booking_idx` (`booking_id`)
);
