CREATE TABLE IF NOT EXISTS biopool_checkout_orders (
  id int AUTO_INCREMENT PRIMARY KEY,
  public_token varchar(64) NOT NULL UNIQUE,
  service_id int NOT NULL,
  booking_id int NULL,
  client_name varchar(200) NOT NULL,
  client_email varchar(320) NOT NULL,
  client_phone varchar(40) NOT NULL,
  booking_date date NOT NULL,
  start_time varchar(5) NOT NULL,
  end_time varchar(5) NOT NULL,
  adult_quantity int NOT NULL,
  child_quantity int NOT NULL DEFAULT 0,
  total_guests int NOT NULL,
  subtotal_clp int NOT NULL,
  discount_clp int NOT NULL DEFAULT 0,
  discount_code_id int NULL,
  discount_code varchar(50) NULL,
  total_clp int NOT NULL,
  status enum('initiating','payment_pending','paid','rejected','aborted','timeout','expired','failed') NOT NULL DEFAULT 'initiating',
  expires_at timestamp NOT NULL,
  webpay_token varchar(180) NULL UNIQUE,
  buy_order varchar(26) NULL UNIQUE,
  session_id varchar(61) NULL,
  webpay_status varchar(40) NULL,
  response_code int NULL,
  authorization_code varchar(80) NULL,
  card_number varchar(40) NULL,
  payment_type_code varchar(10) NULL,
  transaction_date varchar(60) NULL,
  raw_response mediumtext NULL,
  error text NULL,
  utm_source varchar(100) NULL,
  utm_medium varchar(100) NULL,
  utm_campaign varchar(100) NULL,
  paid_at timestamp NULL,
  completed_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX biopool_checkout_hold_idx (service_id, booking_date, status, expires_at),
  INDEX biopool_checkout_booking_idx (booking_id),
  INDEX biopool_checkout_created_idx (created_at)
);

CREATE TABLE IF NOT EXISTS biopool_checkout_items (
  id int AUTO_INCREMENT PRIMARY KEY,
  order_id int NOT NULL,
  ticket_type_id int NOT NULL,
  code varchar(40) NOT NULL,
  name varchar(120) NOT NULL,
  unit_price_clp int NOT NULL,
  quantity int NOT NULL,
  subtotal_clp int NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX biopool_checkout_items_order_idx (order_id)
);
