import { describe, expect, it } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";
import {
  CANCAGUA_STAFF_ROLE,
  MASSAGE_THERAPIST_ROLE,
  canAccessCmsPath,
  getEffectiveCmsPermissions,
  hasCmsPermission,
  hasB2CAccess,
  hasMaintenanceAccess,
  hasMassageAdminAccess,
  hasMassageOperationsAccess,
  hasMassagePaymentAccess,
  hasMassageReadAccess,
} from "../shared/permissions";

function createStaffContext(): TrpcContext {
  return {
    user: {
      id: 2280001,
      openId: "cancagua-staff-test",
      email: "contacto@cancagua.cl",
      name: "Recepción",
      passwordHash: null,
      loginMethod: "email",
      role: CANCAGUA_STAFF_ROLE,
      status: "active",
      allowedModules: null,
      invitationToken: null,
      invitationExpiresAt: null,
      resetToken: null,
      resetTokenExpiresAt: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      lastSignedIn: new Date(),
    },
    req: { protocol: "https", headers: {} } as TrpcContext["req"],
    res: { clearCookie: () => {}, cookie: () => {} } as unknown as TrpcContext["res"],
  };
}

function createMassageTherapistContext(permissions?: string): TrpcContext {
  const context = createStaffContext();
  return {
    ...context,
    user: {
      ...context.user!,
      openId: "massage-therapist-test",
      email: "terapeuta@example.com",
      name: "Terapeuta",
      role: MASSAGE_THERAPIST_ROLE,
      permissions: permissions ?? null,
    },
  };
}

describe("Usuario Personal Cancagua permissions", () => {
  it("allows B2C, maintenance and massage operations", () => {
    expect(hasB2CAccess(CANCAGUA_STAFF_ROLE)).toBe(true);
    expect(hasMaintenanceAccess(CANCAGUA_STAFF_ROLE)).toBe(true);
    expect(hasMassageOperationsAccess(CANCAGUA_STAFF_ROLE)).toBe(true);
    expect(hasMassagePaymentAccess({ role: CANCAGUA_STAFF_ROLE })).toBe(true);
  });

  it("denies massage administration", () => {
    expect(hasMassageAdminAccess(CANCAGUA_STAFF_ROLE)).toBe(false);
  });

  it("allows reception to open the Skedu program booking flow", async () => {
    const caller = appRouter.createCaller(createStaffContext());
    await expect(caller.masajes.agenda.getSkeduPrograms()).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ value: "reconecta_detox", durations: [30, 50] }),
        expect.objectContaining({ value: "bio_reconecta_detox", durations: [30, 50] }),
        expect.objectContaining({ value: "reset", durations: [30] }),
      ])
    );
  });

  it("allows only the requested CMS routes", () => {
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/clientes")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/reportes-mantencion")).toBe(true);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/agenda")).toBe(true);

    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/cotizaciones")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/concierge/venta")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/marketing")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/analytics")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/usuarios")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/tecnicas")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/terapeutas")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/inventario")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/clientes")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/analytics")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/rrhh")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/configuracion")).toBe(false);
  });

  it("blocks restricted massage mutations at the API", async () => {
    const caller = appRouter.createCaller(createStaffContext());

    await expect(caller.masajes.tecnicas.create({
      name: "Técnica restringida",
      durations: "50",
    })).rejects.toMatchObject({ code: "FORBIDDEN" });

    await expect(caller.masajes.terapeutas.create({
      name: "Terapeuta restringida",
      type: "inhouse",
      leadTimeMinutes: 120,
      callPriority: 99,
    })).rejects.toMatchObject({ code: "FORBIDDEN" });

    await expect(caller.masajes.inventario.create({
      name: "Insumo restringido",
      unit: "unidad",
      currentStock: "0",
      minimumStock: "0",
    })).rejects.toMatchObject({ code: "FORBIDDEN" });

    await expect(caller.masajes.disponibilidad.upsertDay({
      therapistId: 1,
      date: "2026-07-15",
      isAvailable: 1,
      autoGenerated: 0,
    })).rejects.toMatchObject({ code: "FORBIDDEN" });
  });
});

describe("Terapeuta de Masajes permissions", () => {
  it("has massage read access but no operational or administrative access", () => {
    expect(hasMassageReadAccess(MASSAGE_THERAPIST_ROLE)).toBe(true);
    expect(hasMassageOperationsAccess(MASSAGE_THERAPIST_ROLE)).toBe(false);
    expect(hasMassageAdminAccess(MASSAGE_THERAPIST_ROLE)).toBe(false);
    expect(hasB2CAccess(MASSAGE_THERAPIST_ROLE)).toBe(false);
    expect(hasMaintenanceAccess(MASSAGE_THERAPIST_ROLE)).toBe(false);
  });

  it("can only open the CMS home, massage dashboard and massage agenda", () => {
    expect(canAccessCmsPath(MASSAGE_THERAPIST_ROLE, "/cms")).toBe(true);
    expect(canAccessCmsPath(MASSAGE_THERAPIST_ROLE, "/cms/masajes")).toBe(true);
    expect(canAccessCmsPath(MASSAGE_THERAPIST_ROLE, "/cms/masajes/agenda")).toBe(true);

    expect(canAccessCmsPath(MASSAGE_THERAPIST_ROLE, "/cms/masajes/terapeutas")).toBe(false);
    expect(canAccessCmsPath(MASSAGE_THERAPIST_ROLE, "/cms/masajes/analytics")).toBe(false);
    expect(canAccessCmsPath(MASSAGE_THERAPIST_ROLE, "/cms/reservas")).toBe(false);
    expect(canAccessCmsPath(MASSAGE_THERAPIST_ROLE, "/cms/usuarios")).toBe(false);
  });

  it("blocks operational actions at the API even if called directly", async () => {
    const caller = appRouter.createCaller(createMassageTherapistContext());

    await expect(caller.masajes.agenda.getSkeduPrograms())
      .rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller.masajes.agenda.updateStatus({ id: 1, status: "completed" }))
      .rejects.toMatchObject({ code: "FORBIDDEN" });
    await expect(caller.giftCardsAdmin.getAll())
      .rejects.toMatchObject({ code: "FORBIDDEN" });
  });

  it("allows an explicitly authorized therapist to assign massages without exposing sales", async () => {
    const permissions = JSON.stringify([
      "module.massages",
      "massages.assign_therapists",
    ]);
    const context = createMassageTherapistContext(permissions);
    const caller = appRouter.createCaller(context);

    expect(hasCmsPermission(context.user!, "massages.assign_therapists")).toBe(true);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/masajes/agenda",
      0,
      permissions,
    )).toBe(true);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/masajes/analytics",
      0,
      permissions,
    )).toBe(false);

    await expect(caller.masajes.agenda.getSkeduProgramResources({
      bookingDate: "2026-07-29",
      startTime: "12:00",
      duration: 30,
      modality: "simple",
    })).resolves.toEqual(expect.objectContaining({
      therapists: expect.any(Array),
      rooms: expect.any(Array),
    }));

    await expect(caller.masajes.agenda.updateStatus({ id: 1, status: "completed" }))
      .rejects.toMatchObject({ code: "FORBIDDEN" });
  });

  it("allows explicitly authorized reception users to manage the agenda without other modules", async () => {
    const permissions = JSON.stringify([
      "module.massages",
      "massages.manage_agenda",
      "massages.assign_therapists",
    ]);
    const context = createMassageTherapistContext(permissions);
    const caller = appRouter.createCaller(context);

    await expect(caller.masajes.agenda.getSkeduPrograms()).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ value: "reconecta" }),
      ]),
    );
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/masajes/agenda",
      0,
      permissions,
    )).toBe(true);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/reservas",
      0,
      permissions,
    )).toBe(false);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/masajes/analytics",
      0,
      permissions,
    )).toBe(false);
    await expect(caller.masajes.agenda.update({ id: 1, paymentStatus: "paid" }))
      .rejects.toMatchObject({ code: "FORBIDDEN" });
  });

  it("allows reception to open only Gift Cards without exposing other sales channels", () => {
    const permissions = JSON.stringify([
      "module.massages",
      "massages.manage_agenda",
      "massages.assign_therapists",
      "module.gift_cards",
    ]);

    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/gift-cards-sales",
      0,
      permissions,
    )).toBe(true);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/concierge/venta",
      0,
      permissions,
    )).toBe(false);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/clientes",
      0,
      permissions,
    )).toBe(false);
  });

  it("allows reception to manage agenda payments without opening massage analytics", () => {
    const permissions = JSON.stringify([
      "module.massages",
      "massages.manage_agenda",
      "massages.assign_therapists",
      "massages.manage_payments",
    ]);

    const user = { role: MASSAGE_THERAPIST_ROLE, permissions };
    expect(hasMassagePaymentAccess(user)).toBe(true);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/masajes/agenda",
      0,
      permissions,
    )).toBe(true);
    expect(canAccessCmsPath(
      MASSAGE_THERAPIST_ROLE,
      "/cms/masajes/analytics",
      0,
      permissions,
    )).toBe(false);
  });

  it("keeps payment details hidden from agenda-only users", () => {
    expect(hasMassagePaymentAccess({
      role: MASSAGE_THERAPIST_ROLE,
      permissions: JSON.stringify([
        "module.massages",
        "massages.manage_agenda",
      ]),
    })).toBe(false);
  });

  it("keeps Gift Cards available to existing users of the Sales module", () => {
    expect(canAccessCmsPath(
      "editor",
      "/cms/gift-cards-sales",
      0,
      JSON.stringify(["module.sales"]),
    )).toBe(true);
  });

  it("treats an explicit empty permission list as removal of legacy role access", () => {
    expect(getEffectiveCmsPermissions({
      role: "admin",
      permissions: "[]",
    })).toEqual([]);
    expect(canAccessCmsPath("admin", "/cms/analytics", 0, "[]")).toBe(false);
  });

  it("keeps granular permission changes exclusive to super administrators", async () => {
    const caller = appRouter.createCaller(createStaffContext());
    await expect(caller.users.updatePermissions({
      userId: 2,
      permissions: ["module.massages"],
    })).rejects.toMatchObject({ code: "FORBIDDEN" });
  });
});
