import { describe, expect, it } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";
import {
  CANCAGUA_STAFF_ROLE,
  canAccessCmsPath,
  hasB2CAccess,
  hasMaintenanceAccess,
  hasMassageAdminAccess,
  hasMassageOperationsAccess,
} from "../shared/permissions";

function createStaffContext(): TrpcContext {
  return {
    user: {
      id: 2280001,
      openId: "cancagua-staff-test",
      email: "contacto@cancagua.cl",
      name: "Recepción",
      passwordHash: null,
      loginMethod: "email",
      role: CANCAGUA_STAFF_ROLE,
      status: "active",
      allowedModules: null,
      invitationToken: null,
      invitationExpiresAt: null,
      resetToken: null,
      resetTokenExpiresAt: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      lastSignedIn: new Date(),
    },
    req: { protocol: "https", headers: {} } as TrpcContext["req"],
    res: { clearCookie: () => {}, cookie: () => {} } as unknown as TrpcContext["res"],
  };
}

describe("Usuario Personal Cancagua permissions", () => {
  it("allows B2C, maintenance and massage operations", () => {
    expect(hasB2CAccess(CANCAGUA_STAFF_ROLE)).toBe(true);
    expect(hasMaintenanceAccess(CANCAGUA_STAFF_ROLE)).toBe(true);
    expect(hasMassageOperationsAccess(CANCAGUA_STAFF_ROLE)).toBe(true);
  });

  it("denies massage administration", () => {
    expect(hasMassageAdminAccess(CANCAGUA_STAFF_ROLE)).toBe(false);
  });

  it("allows reception to open the Skedu program booking flow", async () => {
    const caller = appRouter.createCaller(createStaffContext());
    await expect(caller.masajes.agenda.getSkeduPrograms()).resolves.toEqual(
      expect.arrayContaining([
        expect.objectContaining({ value: "reconecta_detox", durations: [30, 50] }),
        expect.objectContaining({ value: "bio_reconecta_detox", durations: [30, 50] }),
        expect.objectContaining({ value: "reset", durations: [30] }),
      ])
    );
  });

  it("allows only the requested CMS routes", () => {
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/clientes")).toBe(true);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/reportes-mantencion")).toBe(true);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/agenda")).toBe(true);

    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/cotizaciones")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/concierge/venta")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/marketing")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/analytics")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/usuarios")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/tecnicas")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/terapeutas")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/inventario")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/clientes")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/analytics")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/rrhh")).toBe(false);
    expect(canAccessCmsPath(CANCAGUA_STAFF_ROLE, "/cms/masajes/configuracion")).toBe(false);
  });

  it("blocks restricted massage mutations at the API", async () => {
    const caller = appRouter.createCaller(createStaffContext());

    await expect(caller.masajes.tecnicas.create({
      name: "Técnica restringida",
      durations: "50",
    })).rejects.toMatchObject({ code: "FORBIDDEN" });

    await expect(caller.masajes.terapeutas.create({
      name: "Terapeuta restringida",
      type: "inhouse",
      leadTimeMinutes: 120,
      callPriority: 99,
    })).rejects.toMatchObject({ code: "FORBIDDEN" });

    await expect(caller.masajes.inventario.create({
      name: "Insumo restringido",
      unit: "unidad",
      currentStock: "0",
      minimumStock: "0",
    })).rejects.toMatchObject({ code: "FORBIDDEN" });

    await expect(caller.masajes.disponibilidad.upsertDay({
      therapistId: 1,
      date: "2026-07-15",
      isAvailable: 1,
      autoGenerated: 0,
    })).rejects.toMatchObject({ code: "FORBIDDEN" });
  });
});
